export default {
  levelCoors: {
    1: '#B6B6B6',
    2: '#B6B6B6',
    3: '#B6B6B6',
    4: '#9C07FF',
    5: '#9C07FF',
    6: '#9C07FF',
    7: '#9C07FF',
    8: '#FFCD07',
    9: '#FFCD07',
    10: '#FFCD07',
  },
  profession: {
    0: 'Omni Warrior',
    1: 'Psionicist',
    2: 'Bounty Hunter',
    3: 'Wanderer',
    4: 'Liquidator',
  },
  rarityImage: {
    0: '/cardbg1.png',
    1: '/cardbg2.png',
    2: '/cardbg3.png',
    3: '/cardbg4.png',
    7: '/card-bg-material.png',
    epic: '/card-bg-material.png',
  },
  levelImage: {
    1: '/lv1.png',
    2: '/lv2.png',
    3: '/lv3.png',
    4: '/lv4.png',
    5: '/lv5.png',
    6: '/lv6.png',
  },
  rarity: {
    0: 'Common',
    1: 'Rare',
    2: 'Epic',
    3: 'Legend',
  },
  material: {
    0: 'DarkIron',
    1: 'Silver',
    2: 'Gold',
  },
  identity: {
    0: 'Leader',
    1: 'Scientist',
    2: 'Commander',
    3: 'Star Soldier',
    4: 'Common Soldier',
  },
  identityImages: {
    0: 'leader',
    1: 'scientist',
    2: 'commander',
    3: 'star_soldier',
    4: 'common_soldier',
  },
  camp: {
    0: 'Asman Zerg',
    1: 'Empire of Amda',
    2: 'Confederation of Earth',
    3: 'Eternal Protoss',
  },
  egseType: {
    1: 'NORMAL',
    2: 'RARE',
    3: 'EPIC',
  },
  pseType: {
    1: 'TypeI',
    2: 'TypeII',
    3: 'Star',
    4: 'Galaxy',
    5: 'Eternal',
    6: 'blackbox',
    7: 'golddigger',
    8: 'Trabilizer',
  },
  eggType: {
    1: 'Confederation Of Earth',
    2: 'Empire of Amda',
    3: 'Asman Zerg',
    3: 'Eternal Protoss',
  },
  spaceshipType: {
    1: 'common',
    2: 'Rare',
    3: 'Epic',
    4: 'Legend',
  },
  equipType: {
    1: 'Common',
    2: 'Rare',
    3: 'Epic',
    4: 'Legendary',
  },
  spaceshipTypeColor: {
    COMMON: '#8696C0',
    RARE: '#29BDFF',
    EPIC: '#9D00FF',
    LEGENDARY: '#FFD800',
  },
  lootBoxType: {
    1:'Halloween Loot Box',
    2:'EGSE_Normal',
    3:'EGSE_Rare',
    4:'EGSE_Epic',
    5:'Standard Loot Box',
    6:'Premium Loot Box',
    7:'Epic Loot Box',
    8:'Legendary Loot Box',
    9:'Collection Loot Box',
    10:'Identity Loot Box-Commander',
    11:'Identity Loot Box-Scientist',
    12:'Identity Loot Box -Star soldier',
    13:'Identity Loot Box-Common soldier',
    14:'Faction Loot box -Confederation of Earth',
    15:'Faction Loot box -Asman Zerg',
    16:'Faction Loot box -Empire of Amda',
    17:'Faction Loot box -Eternal Protoss',
    18:'Spaceship Loot Box',
    19:'V3-Galaxy Loot Box',
    20:'Kandal\'s Relic',
  },
  materialType: {
    1: 'Common',
    2: 'Rare',
    3: 'Epic',
    4: 'legend',
  },
  cardType: {
    card: 0,
    halloween: 1,
    pse: 2,
    egse: 3,
    spaceship: 4,
    lootbox: 6,
    material: 8,
    egg: 5,
    equipment: 7,
    // weapon: 10,
  },
  equipmentType: {
    '01': "Protector Helmet",
    '02': "Energy Cuirass",
    '03': "Protector Leggings",
    '04': "Protector Cuirass",
    '05': "Kandal's Helmet",
    '06': "Kandal's Cuirass",
    '07': "Kandal's Leggings",
    '08': "Spectre Cuirass",
    '09': "Marauders Cuirass",
    '10': "Marauders Leggings",
    '11': "Marauders Helmet",
    '12': "Multi-thread",
    '13': "Lacerator",
    '14': "Marauders Rifle",
    '15': "Marauders Pistol",
    '16': "Kandal's Sword",
    '17': "Kandal's Sharp Claws",
  }
};
